display_name: Logbay
publisher_display_name: Logbay
identity_name: com.gyanoba.logbay
msix_version: 1.5.6.56
logo_path: macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png
architecture: x64
publisher: CN=Logbay
sign_msix: "false"
install_certificate: "false"
